name: CI

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  dart:
    permissions:
      contents: read
    uses: famedly/frontend-ci-templates/.github/workflows/dart.yml@aa793b1fe31af74beb3f2a8e450a0da7dccde65c
    with:
      env_file: ".github/workflows/versions.env"
    secrets:
      ssh_key: "${{ secrets.CI_SSH_PRIVATE_KEY }}"

  general:
    permissions:
      contents: read
    uses: famedly/frontend-ci-templates/.github/workflows/general.yml@aa793b1fe31af74beb3f2a8e450a0da7dccde65c

  app_jobs:
    secrets: inherit
    uses: ./.github/workflows/app.yml
